# Generated by Django 5.1.7 on 2025-04-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf3', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
