# Generated by Django 5.1.7 on 2025-04-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='title',
            field=models.CharField(default='Sans titre', max_length=255),
        ),
        migrations.AddField(
            model_name='dossier',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
