# Generated by Django 5.1.7 on 2025-04-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0003_dossier_title_dossier_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
