# Generated by Django 5.1.7 on 2025-04-14 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_dossier_user_id_alter_dossier_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='pdf3',
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='Bookstore.dossier')),
            ],
        ),
    ]
