# Generated by Django 5.1.7 on 2025-04-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0005_remove_dossier_pdf3_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='dossier',
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
