# Generated by Django 6.0.1 on 2026-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='depuis_formulaire',
            field=models.BooleanField(default=False),
        ),
    ]
