# Generated by Django 6.0.1 on 2026-01-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0002_piecejointe_depuis_formulaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piecejointe',
            old_name='depuis_formulaire',
            new_name='depuis_formulaire_ajout_piecejointe_dossier_par_admin',
        ),
    ]
