# Generated by Django 6.0 on 2026-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
