# Generated by Django 6.0 on 2026-01-31 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0006_rename_user_chat_sender_alter_chat_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='procedure_app.dossier'),
        ),
    ]
