# Generated by Django 6.0 on 2026-01-31 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0011_alter_chat_conversation_alter_chat_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='procedure_app.dossier'),
        ),
    ]
