# Generated by Django 6.0.1 on 2026-02-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0013_deleterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseJuridiqueDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_article', models.CharField(help_text="Numéro de l'article (ex: Article 74)", max_length=50)),
                ('titre_article', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('FAVORABLE', 'Favorable au client'), ('DEFAVORABLE', 'Défavorable au client'), ('NEUTRE', 'Neutre')], max_length=20)),
                ('analyse', models.TextField(help_text="Analyse détaillée générée par l'IA")),
                ('recommandations', models.TextField(blank=True, help_text="Recommandations pratiques pour l'avocat")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_juridiques', to='procedure_app.dossier')),
            ],
            options={
                'verbose_name': 'Analyse juridique',
                'verbose_name_plural': 'Analyses juridiques',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['dossier', 'categorie'], name='procedure_a_dossier_c21e9a_idx'), models.Index(fields=['date_creation'], name='procedure_a_date_cr_38a905_idx')],
            },
        ),
    ]
