# Generated by Django 6.0.1 on 2026-02-07 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0014_analysejuridiquedossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultats_json', models.JSONField(default=dict)),
                ('resume', models.TextField(blank=True)),
                ('articles_favorables', models.TextField(blank=True)),
                ('articles_defavorables', models.TextField(blank=True)),
                ('amendes', models.TextField(blank=True)),
                ('sanctions', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('conseils', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', "En cours d'analyse"), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='analysejuridiquedossier',
            name='procedure_a_dossier_c21e9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysejuridiquedossier',
            name='procedure_a_date_cr_38a905_idx',
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_juridiques', to='procedure_app.dossier'),
        ),
        migrations.DeleteModel(
            name='AnalyseJuridiqueDossier',
        ),
    ]
