# Generated by Django 6.0.1 on 2026-02-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0015_analysejuridique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysejuridique',
            name='conseils',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='date_analyse',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='resultats_json',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='statut',
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='article_references',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='modele_ia_utilise',
            field=models.CharField(default='mixtral-8x7b-32768', max_length=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='analyse_effectuee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='amendes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='articles_defavorables',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='articles_favorables',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='procedure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='sanctions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='description_affaire',
            field=models.TextField(),
        ),
    ]
