# Generated by Django 6.0.1 on 2026-02-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0016_remove_analysejuridique_conseils_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('source', models.CharField(default='Code pénal camerounais', max_length=200)),
            ],
            options={
                'verbose_name': 'Article juridique',
                'verbose_name_plural': 'Articles juridiques',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysejuridique',
            options={'ordering': ['-date_analyse'], 'verbose_name': 'Analyse juridique', 'verbose_name_plural': 'Analyses juridiques'},
        ),
        migrations.RenameField(
            model_name='analysejuridique',
            old_name='date_creation',
            new_name='date_analyse',
        ),
        migrations.RenameField(
            model_name='analysejuridique',
            old_name='amendes',
            new_name='recommandations',
        ),
        migrations.RenameField(
            model_name='analysejuridique',
            old_name='articles_defavorables',
            new_name='resume_analyse',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='article_references',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='articles_favorables',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='modele_ia_utilise',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='sanctions',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='analyse_effectuee',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='date_analyse',
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='source_articles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='articles_concernes',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='procedure_app.articlejuridique'),
        ),
    ]
