# Generated by Django 6.0.1 on 2026-02-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0017_articlejuridique_alter_analysejuridique_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysejuridique',
            name='articles_concernes',
        ),
        migrations.AlterModelOptions(
            name='analysejuridique',
            options={},
        ),
        migrations.RenameField(
            model_name='analysejuridique',
            old_name='date_analyse',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='resume_analyse',
        ),
        migrations.RemoveField(
            model_name='analysejuridique',
            name='source_articles',
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='delais_importants',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='demarches_recommandees',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='nature_juridique',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='procedure_complete',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='questions_frequentes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='risques_juridiques',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysejuridique',
            name='textes_applicables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysejuridique',
            name='recommandations',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('reponse', models.TextField(default='')),
                ('date_question', models.DateTimeField(auto_now_add=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='procedure_app.analysejuridique')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleJuridique',
        ),
    ]
